language: java
sudo: false

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: openjdk11
      env:
        - _JAVA_OPTIONS="--add-opens=java.base/java.util=ALL-UNNAMED -Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw"

addons:
  apt:
    packages:
      - openjdk-11-jdk

script: >-
    ./config/travis/run-checks.sh &&
    ./gradlew clean checkstyleMain checkstyleTest test coverage coveralls asciidoctor

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/